// Runs after wasm-bindgen. Embeds the .wasm file in a JS module as base64, so
// `init()` needs no argument anywhere, and removes the glue's default of
// fetching the .wasm file from next to it: the published package makes no
// network requests. Fails the build if the glue no longer looks as expected.
import { readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../src/wasm/", import.meta.url);
const gluePath = new URL("format_png_wasm.js", dir);

function replaceOnce(source, search, replacement) {
    const count = source.split(search).length - 1;
    if (count !== 1) {
        throw new Error(`inline-wasm: expected the wasm-bindgen glue to contain this exactly once, found ${count}:\n${search}`);
    }
    return source.replace(search, () => replacement);
}

let glue = readFileSync(gluePath, "utf8");
glue = replaceOnce(
    glue,
    `    if (module_or_path === undefined) {
        module_or_path = new URL('format_png_wasm_bg.wasm', import.meta.url);
    }
`,
    `    if (module_or_path === undefined) {
        throw new Error("format-png: no WebAssembly module given");
    }
`,
);
glue = replaceOnce(
    glue,
    `    if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
        module_or_path = fetch(module_or_path);
    }
`,
    "",
);
if (/\bfetch\s*\(/.test(glue)) throw new Error("inline-wasm: the wasm-bindgen glue still calls fetch");
writeFileSync(gluePath, glue);

const base64 = readFileSync(new URL("format_png_wasm_bg.wasm", dir)).toString("base64");
writeFileSync(
    new URL("format_png_wasm_bg.wasm.base64.js", dir),
    `// format_png_wasm_bg.wasm, base64-encoded. Generated by scripts/inline-wasm.mjs\n// from the wasm-bindgen output of crates/format-png-wasm; don't edit.\nexport default "${base64}";\n`,
);
writeFileSync(
    new URL("format_png_wasm_bg.wasm.base64.d.ts", dir),
    "/** `format_png_wasm_bg.wasm`, base64-encoded. */\ndeclare const wasm: string;\nexport default wasm;\n",
);
